# Generated by Django 4.1 on 2022-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emisor', models.CharField(max_length=150)),
                ('id_receptor', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
