# Generated by Django 4.1 on 2022-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMensaje', '0002_remove_mensaje_id_emisor_remove_mensaje_id_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
