# Generated by Django 4.1 on 2022-10-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMensaje', '0003_mensaje_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='mensaje',
        ),
    ]
