# Generated by Django 4.1 on 2022-10-11 19:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMensaje', '0004_remove_mensaje_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='mensaje',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
