# Generated by Django 4.1 on 2022-10-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('cuerpo', models.TextField()),
            ],
        ),
    ]
