# Generated by Django 4.1 on 2022-10-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
