# Generated by Django 4.1.2 on 2022-10-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0004_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fechaPublicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
